var citater = [
    "??-??-???? Random person fra rollespil: Hvorfor kyssede du hende ikke?",
    "{ML} Alfred: Fordi vi var til rollespil, og det ville være meget underligt.",
    "{ML} Random person: Det er dårligt rollespil!",
    "??-??-20xx Vitus: Det er ikke en kappe, det er en tabard!",
    "??-??-2019 Emil: Piger er nogle girakkere.",
    "??-??-2019 Leo: vi har nok den mest almindelige klasse på årgangen",
    "{ML}Malthe: lå lå lå lålålålålålå vi har fransk... vi skal mobbe Alia!",
    "29-04-2019 Alfred: ... jeg er meget dybt koncentret i at skrive på et whiteboard.",
    "30-04-2019 Emil: Tænk hvis puden slår igen.",
    "01-05-2019 Emil: Jeg vil til darnhall.",
    "01-05-2019 Rune: Vi ruller lige heroppe.",
    "10-05-2019 Emil: ... han har snakket med kinesere.",
    "07-06-2019 Alfred: Det arger mig at Hitler ikke går i arv.",
    "14-06-2019 Emil: (peger på Alfred) Dit navn er Albert Charlie...",
    "05-08-2019 Benjamin: Yay! 98",
    "06-08-2019 Benjamin: Farven var brun da jeg kiggede på den igår.",
    "06-08-2019 Alfred: Den der lyskore, der kun er farlig når man stikker med den",
    "07-08-2019 Rune: Hvis du vil hårdt nok, så kan du det med alle instrumenter",
    "{ML}Benjamin: Hvad med en didgeridoo?",
    "07-08-2019 Emil: I er godt klar over, at jo flere i spiser, jo hurtigere er den tom",
    "07-08-2019 Benjamin: Den her popcorn smager lidt af gummi",
    "{ML}Alfred: Det er fordi at den er gummi agtig.",
    "{ML}Rune: Det sagde hun også igår.",
    "09-08-2019 Alfred: De er mest røvhul.",
    "12-08-2019 Alfred: Du sagde at du ville være med i dem.",
    "{ML}Benjamin: Men jeg vil ikke have en hat!",
    "12-08-2019 Adrian: Nimar er en jerk.",
    "12-08-2019 Emil: Er det dig der hedder stark?",
    "12-08-2019 Adrian: Hvis man tager alting ud af kontekst så tror man at vi er sådan nogen maniacs",
    "12-08-2019 Adrian: Yoda siger: \"Hvis at du vil have min ananas, så skal du give mig 30 kroner\"",
    "12-08-2019 Alfred: Jeg siger at du er blå!",
    "{ML}Adrian: Jeg siger at du er grøn!",
    "12-08-2019 Adrian: Jeg vidste ikke at fisgur var inden for sex.",
    "12-08-2019 Alfred: Jeg kan altså ikke se ideen med det der (slår på Adrian med en pude).",
    "12-08-2019 Adrian: Nej jeg er ikke fisgur!",
    "12-08-2019 Vitus: Men vi vil have en millitærbase!",
    "13-08-2019 Alfred: Piger er så fucking udspekulerede.",
    "{ML}Alfred: Hun er ligesom Hermione Granger!",
    "13-08-2019 Adrian: Nej det må du ikke Yoda!",
    "{ML}Adrian: Du må ikke sælge mig ananas!",
    "13-08-2019 Laura: Du er så fucking provokerende",
    "{ML}Emil: Ja, det er det jeg kan.",
    "13-08-2019 Tristan: Det forstår jeg intet af.",
    "{ML}Emil: Banan 39 46 Jørgen",
    "13-08-2019 Alfred: Fuck dig, hele din famillie, alt hvad du står for og alt hvad du har opnået hele dit liv!",
    "14-08-2019 Edina (vores matlærer): Nej, 1 divideret med 5 er ikke 1.",
    "13-08-2019 Carla (en tidligere klassekammerat): Lad være, jeg har selv stjålet den!",
    "13-08-2019 Martin (vores dansklærer): Jeg bruger ikke meget af min hjernekapacitet på at tænke over, hvad dumme mennesker gør og ikke gør.",
    "14-08-2019 Adrian: Vidste du at djorka er et synonym for min far er bedre end din far?",
    "{ML}Alfred: Ja det er rigtigt fordi Ragiiiil!",
    "15-08-2019 Thilde (en klassekammerat fra S): Lad ham sove, ellers så dør han!",
    "15-08-2019 Vitus: Jaidouzeans (udtalet [chaidusang])",
    "15-08-2019 Elton: (lugter til en squishy) Ad den stinker... Den er giftig!",
    "16-08-2019 Benjamin: Halvejs igennem hoppet, huskede jeg at jeg kun havde 1 liv...",
    "20-08-2019 Lili-Luna: Kan i ikke lige have sex et andet sted?",
    "26-08-2019 Alfred: Man skulle forfanden tro at du står i ledtog med Dansk Folkeparti.",
    "29-08-2019 Rune: Glæd dig til at jeg får flere liv end dig.",
    "{ML}Jakob: Nej, du må ikke skifte karekter, jeg eeelsker dig!",
    "30-08-2019 Vitus: Don't give the dragon an exsitensial crisis.",
    "30-08-2019 Adrian: Kan vi ikke sige, at jeg har en backpack med mine hoveder i?",
    "30-08-2019 Rune: Jeg kan ikke fejle.",
    "{ML}Emil: Whaao, stem på mig.",
    "30-08-2019 Rune: Giv mig noget kattemad, så kan vi finde ud af det.",
    "02-09-2019 Vitus: Er det nu et achivement at narre mig?",
    "{ML}Benjamin: Jeg har et achivement på dig: At dræbe dig to gange",
    "03-09-2019 Elton: Jeg leger at jeg er retaderet.",
    "19-08-2019 Villads W: Det er ikke din sexdukke, Chanel",
    "29-08-2019 En eller anden rollespiller: Fuck ragil.",
    "{ML}Alfred: NEEJ, du må ik kysse min ragil!",
    "13-09-2019 Vitus: Hvor er mine ører?",
    "13-09-2019 Emil: Romerriget og Nazityskland sat sammen og sat ind i middelalderen, så har du Emyr.",
    "20-09-2019 Alfred: Du ved godt at jeg har et oneshot sværd ik?",
    "25-09-2019 Vores kodelærer i skolen: ... og så kan man jo lave et intelligent æg.",
    "27-09-2019 Random lille pige: Jeg er ikke lille, jeg går allerede i første klasse",
    "30-09-2019 Leo: Ja, præsist han er fattig, så vi skal bare smide ham ud",
    "30-09-2019 Alfred: I virkeligheden, når nej Warhammer",
    "08-10-2019 Rune: Det er ligemeget, det er min drage, hun gør hvad jeg siger",
    "11-10-2019 Emil: Som person er vitus vidstnok printet af sine forældre",
    "11-10-2019 Alfred: Du skal heller ikke inhalere en orm, bare fordi den er der!",
    "25-10-2019 Benjamin: Jeg gider ikke gå igennem puberteten igen.",
    "28-10-2019 Emil: Jeg har ikke tænkt mig at tave pave snakken lige nu.",
    "07-11-2019 Emil (klassekammerat) din filipinske fisk!",
    "08-11-2019 Vitus: Vi skal købe flere børn, så vi kan avle dem",
    "08-11-2019 Emil: Man rør ikke bare med en tohåndshammer",
    "08-11-2019 Benjamin: It's not rape, it's surprice sex",
    "08-11-19 Adrian: Tak for barnet",
    "{ML}Alfred: Det sagde hun også igår",
    "15-11-2019 Mikkel: Yakup, skal jeg seriøst konfiskere din sko?",
    "19-11-2019 Mikkel: Nej nu blev den lidt for lang, så gør vi det igen",
    "19-11-2019 Mikkel: Yakup, tror du også at den skal derind?",
    "{ML}Yakup: Nej jeg ved ikke hvor den skal ind!",
    "26-11-2019 Vitus: i har nu adgang til slaver",
    "Laura 26-11-2019: Ej hvor er du voldsom du siger piksvin",
    "{ML}Benjamin: Ja, til mine venner. Det må man godt gøre.",
    "29-11-2019 Alfred: Bare rolig, alt er under kontrol, jeg er ved at blive fanget",
    "02-12-2019 Benjamin: Han gemmer den mellem benene!",
    "{ML}Vitus: Det sagde hun også igår",
    "02-12-2019 En fra M3: how do you say \"its not rape if im swag\" in danish?",
    "01-09-2020 Willas fra Adrians klasse: Hygge er drugs",
    "03-12 2019 Asger M: Lederen af bortløbene slaver skal knippes 3 gange og derefter hænges",
    "04-12-2019 Alfred: Mor og morder minder om hinanden",
    "{ML}Ferdinand: Ja, hvis de har fået en abort",
    "05-12-2019 Luca: Jeg kunne ikke se dig, du er helt sort",
    "06-12-2019 Aske: Sex er en full action",
    "06-12-2019 Vitus: Alfred, er mine tænder skarpe?",
    "{ML}Alfred: Jeg kender svaret, men vil ikke sige det",
    "07-12-2019 Ferdinand: Så det du siger er at, Maria er blevet phykisk voldtaget af gud?",
    "10-12-2019 Aske: Okay, sig til din far at vi har givet dig opgaven som husslave fordi at du er kvinde",
    "11-12-2019 Mikkel: Elton, skal jeg seriøst konfiskere din soya?",
    "12-12-2019 Laura: Shit en rapunsel wannabe",
    "12-12-2019 Alfred: Vitus jeg bider i den",
    "12-12-2019 Alfred: Jeg kunne rent faktisk ikke mærke ham",
    "13-12-2019 Aske: Det er fast luft som ikke gør ondt.",
    "13-12-2019 Adrian: Hvor meget salt har du lige?",
    "{ML}Aske: Uendeligt, jeg har havet!",
    "13-12-2019 Emil: Det har vi jo snakket om at jeg ikke må fortælle i kuglen.",
    "13-12-2019 Emil som en karekter: Nej herre, du kan ikke snyde mig.",
    "{ML}Adrian: Nå, men så hypnotiserer jeg ham",
    "13-12-2019 Mikkel: Nogen af jer der har været i et fattigt land?",
    "{ML}Yakup: Jeg har været hjemme hos Noah",
    "13-12-2019 Vitus: Man laver altså ikke highfive efter et mord.",
    "20-12-2019 Alfred: og så havde adrian selvfølgelig tøj på, i forhold til mig",
    "20-12-2019 Alfred: Elverfyr, tag tøjet af og skaf dig en sele",
    "20-12-2019 Alfred: På det tidspunkt havde han bukserne halvt på.",
    "03-01-2020 Thor fra adrians klasse: Adrian gulerøderne har speedos på!",
    "14-01 2020 Alfred: Der er bryllup ude til life.",
    "{ML}Aske: Er der bryllup?",
    "{ML}Alfred: Ja og det er dårligt rollespil hvis de ikke kysser.",
    "{ML}Aske: Jeg kysser bruden",
    "07-02-2020 Alfred: De er børn, derfor skal de dø",
    "07-02-2020 Rune: Du vil dræbe børn!",
    "{ML}Alfred: Ja, hvad er problemet?",
    "07-02-2020 Aske: Ja vi må gerne slå kvinder ihjel, det er ligemeget",
    "07-02-2020 Alfred: Hvis det er kvinder kan det jo ikke være mænd",
    "20-02-2020 Benjamin: Nårh ja, den her chili brænder jo bare!",
    "Edina: Hvor mange søskende har du asger?",
    "{ML}Asger m: Halvanden",
    "21-02-2020 Aske og Rune: HoP inD i BilEn!",
    "21-02-2020 Alfred: Jeg har fået fri, jeg nægter at vide ting!",
    "02-03-2020 Alfred: skrub ud af mit hus din klamme ting",
    "03-03-2020 Asger M: Ulven er kønsforvirret",
    "07-03-2020 Sigurd: Jeg er ikke deep, jeg er en fucking pige!",
    "23-05-2020 Alfreds 7-årige kusine: Ja, vi skal da have noget mere øl!",
    "24-03-2020 Adrian: Jeg så noget klamt i min kugle!",
    "24-03-2020 Benjamin: Nej lars, du skal ikke spise ledningen!",
    "13-05-2020 Rune: Skal du have hvid maling for så skaffer jeg det",
    "11-06-2020 Benjamin: Min hjerne er ikke klog! Folk tror min hjerne er klog, men det er den ikke!",
    "23-05-2020 Rune: Jeg kan svinge en yoyo op i dilleren hvis jeg får noget for det.",
    "06-07-2020 Rune: Vi bliver jagtet af odense fodboldklub!",
    "06-07-2020 Rune: Kom her DF! Nu skal du dø!",
    "06-07-2020 Adrian: De sidder bare alle sammen og gangbanger en sten",
    "14-08-2020 Adrian: Jeg er ikke alkoholiker, jeg er en dværg",
    "14-08-2020 Vitus: Men, jeg kan ikke købe sjov med taknemmelighed",
    "14-08-2020 Aske: Så gå væk, din store lækre bacon",
    "15-08-2020 Rune: Så der bajer til far mand",
    "28-08-2020 Marta: Lad os gøre alfred til en mand",
    "28-08-2020 David: Madicken, du skal ikke sidde og bide. I må ikke savle på hinanden under coronatiden.",
    "31-08-2020 Rehan: Du er den eneste der har tysk her! Din hitler fan!",
    "03-09-2020 Rehan: Giv mig min stabber, jeg skal stabbe",
    "03-09-20 En pige fra adrians klasse: Dem der har fået 10 skal dø",
    "04-09-2020 Yakup: Sæt dig ned din fucking træstamme! Gå tilbage til randers regnskov med dig!",
    "04-09-2020 Alfreds biologilærer: Jaja, hver weekend så sætter jeg mig på bænkene, drikker nogle øl og graver nogle huler. Don't do drugs, kids!",
    "04-09-2020 Aske: hvem har størst chance for at have sex i en bil?",
    "{ML}Aske: Noah, det er de nigarianske metoder",
    "07-09-2020 Aske: jeg bliver nød til at vide hvordan man simper!",
    "14-09-2020 Adrian: Ytringsfrihed er overvurderet",
    "16-09-2020 Marta: Det er politisk ukorrekt at sige spåkone",
    "18-09 2020 Jens (en lærer i skolen): Den er teknisk set skolens stol...",
    "{ML}Yakup: Nej jeg har selv sat navneskilt på!!",
    "25-09-2020 Emil: Og så føles den varm og pelset",
    "{ML}Alfred: Det sagde hun også i går!",
    "27-09-2020 Alfred og Aske: (overfalder benjamin)",
    "{ML}Aske: Bare rolig, det er bare bromance",
    "{ML}Benjamin: Det her er ikke bromance, det er brape",
    "02-10-2020 Aske: Prøv at høre, vi vil ikke have en alliance med Nordkorea og DF!",
    "02-10-2020 Aske: Hvis det her ikke havde været et børnevenligt rollespil, ville jeg have en pisse god ide til hvordan vi kunne lokke folk til byen",
    "{ML}Emil: Hvornår har det her nogensinde været et børnevenligt rollespil?",
    "02-10-2020 Alfred: Jeg synes at Åndernes herre skal få uendeligt kost og logi i vores slot",
    "{ML}Vitus: I vores <i>horehus</i>, ikke vores slot.",
    "02-10-2020 Alfred: Det eneste vi mangler er bare en fucking sump!",
    "02-10-2020 Aske: Skider vi i en <i>tornebusk</i>?",
    "02-10-2020 Aske: Nogle grundlæg et horehus, jeg gider ikke, det er uærefuldt.",
    "{ML}Alfred: Jeg gør det!",
    "02-10-2020 Alfred: Hvad hedder hun?",
    "{ML}Aske: Jeg ved det ikke!",
    "{ML}Rune: Hun hedder Caroline!",
    "02-10-2020 Aske: Nå, I er her?",
    "{ML}Rune: Velkommen til mit land!",
    "05-10-2020 Marcus: Giv mig nogle piger!",
    "06-10-2020 Christian: hun sagde aldrig stop.",
    "{ML}Benjamin: det sagde han også i går",
    "09-10-2020 Alfred: Kys hende for Flarns navn!",
    "09-10-2020 Aske: Er det her en sædbank eller et bryllup?",
    "09-10-2020 Rune: De blev begge to smidt som børn.",
    "{ML}Emil: Hvad mener du?",
    "{ML}Rune: Ja, altså deres forældre spillede stangtennis med dem.",
    "12-09-2020 Alfred: Altså, jeg vil mene at hun bare gjorde ting på mig og jeg resistede bare ikke",
    "14-10-2020 Rune: Du er Osama Bin Laden øremorder",
    "18-10-2020 Rune: Jeg voldtager de her børn",
    "21-10-2020 Marta: Man kan ikke se hvor stor den er!",
    "22-10-2020 Yakup: Rune din pik!",
    "{ML}Aske: Rune er ikke en pik han er en pære!",
    "25-10-2020 Aske: NEJNEJ, hvorfor bygger den ikke?",
    "25-10-2020 Vitus: Så! Nu knuldrer de!",
    "{ML}Aske: Bliver de liderlige nu?",
    "{ML}Vitus: Ja!",
    "{ML}Aske: Fuck hvor fedt!",
]
window.onload = function () {
    var x = 0
    for (let i = 0; i < citater.length; i++) {
        var src = citater[i].replace(/\: /,'¤').split('¤');
        var person = src[0].replace("{ML}", "")
        var citat = src[1];
        if (person == src[0]) {
            document.getElementById("citater").innerHTML += "<br>" + "<p>" + person + ": \"" + citat + "\"" + "</p>";
            x++
            if(("<br>" + "<p>" + person + ": \"" + citat + "\"" + "</p>").indexOf("undefined")) {console.log({src,citat,person})}
        } else {
            document.getElementById("citater").innerHTML += "<p>" + person + ": \"" + citat + "\"" + "</p>";
        }
        

    }
    document.getElementById("forskelligecitater").textContent = x
}